package com.yalnizfahrettin.azim.data

// GENERATED by tools/build_locales.py. Tables are lazy and shared across all surfaces.
internal object LocaleCatalog {
    fun quotes(language: String): Map<String, String> = when(language) {
        "pt" -> LocalePt.quotes
        "de" -> LocaleDe.quotes
        "fr" -> LocaleFr.quotes
        "it" -> LocaleIt.quotes
        "ru" -> LocaleRu.quotes
        else -> emptyMap()
    }
    fun ui(language: String): Map<String, String> = when(language) {
        "pt" -> LocalePt.ui
        "de" -> LocaleDe.ui
        "fr" -> LocaleFr.ui
        "it" -> LocaleIt.ui
        "ru" -> LocaleRu.ui
        else -> emptyMap()
    }
}
