package com.yalnizfahrettin.azim.ui

import androidx.annotation.DrawableRes
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import com.yalnizfahrettin.azim.R

/** Generated by tools/prepare_category_art.py; every catalogue category has its own image. */
object KategoriResimleri {
    val all: Map<String, Int> = mapOf(
        "ozsefkat" to R.drawable.category_ozsefkat,
        "ic_huzur" to R.drawable.category_ic_huzur,
        "kendine_guven" to R.drawable.category_kendine_guven,
        "motivasyon" to R.drawable.category_motivasyon,
        "azim" to R.drawable.category_azim,
        "pes" to R.drawable.category_pes,
        "zorluk_sabir" to R.drawable.category_zorluk_sabir,
        "yorgunluk_sabir" to R.drawable.category_yorgunluk_sabir,
        "tukenmislik" to R.drawable.category_tukenmislik,
        "yeniden" to R.drawable.category_yeniden,
        "uzun_soluk" to R.drawable.category_uzun_soluk,
        "umut" to R.drawable.category_umut,
        "erteleme" to R.drawable.category_erteleme,
        "derin_odak" to R.drawable.category_derin_odak,
        "durtu" to R.drawable.category_durtu,
        "rutin" to R.drawable.category_rutin,
        "dagilma" to R.drawable.category_dagilma,
        "ozguven" to R.drawable.category_ozguven,
        "korku" to R.drawable.category_korku,
        "reddedilme" to R.drawable.category_reddedilme,
        "risk" to R.drawable.category_risk,
        "utangaclik" to R.drawable.category_utangaclik,
        "marcus" to R.drawable.category_marcus,
        "seneca" to R.drawable.category_seneca,
        "epiktetos" to R.drawable.category_epiktetos,
        "platon" to R.drawable.category_platon,
        "aristoteles" to R.drawable.category_aristoteles,
        "nietzsche" to R.drawable.category_nietzsche,
        "konfucyus" to R.drawable.category_konfucyus,
        "machiavelli" to R.drawable.category_machiavelli,
        "mevlana" to R.drawable.category_mevlana,
        "yunus" to R.drawable.category_yunus,
        "sems" to R.drawable.category_sems,
        "hafiz" to R.drawable.category_hafiz,
        "zen" to R.drawable.category_zen,
        "kuran" to R.drawable.category_kuran,
        "incil" to R.drawable.category_incil,
        "tevrat" to R.drawable.category_tevrat,
        "dua" to R.drawable.category_dua,
        "sukur" to R.drawable.category_sukur,
        "antrenman" to R.drawable.category_antrenman,
        "dayaniklilik" to R.drawable.category_dayaniklilik,
        "sakatlik" to R.drawable.category_sakatlik,
        "sabah_rutini" to R.drawable.category_sabah_rutini,
        "beslenme" to R.drawable.category_beslenme,
        "girisimcilik" to R.drawable.category_girisimcilik,
        "kariyer" to R.drawable.category_kariyer,
        "liderlik" to R.drawable.category_liderlik,
        "para" to R.drawable.category_para,
        "zaman" to R.drawable.category_zaman,
        "basarisizlik" to R.drawable.category_basarisizlik,
        "basari" to R.drawable.category_basari,
        "ask" to R.drawable.category_ask,
        "ayrilik" to R.drawable.category_ayrilik,
        "aile" to R.drawable.category_aile,
        "arkadaslik" to R.drawable.category_arkadaslik,
        "yalnizlik" to R.drawable.category_yalnizlik,
        "affetmek" to R.drawable.category_affetmek,
        "kaygi" to R.drawable.category_kaygi,
        "stres" to R.drawable.category_stres,
        "minnettarlik" to R.drawable.category_minnettarlik,
        "simdiki_an" to R.drawable.category_simdiki_an,
        "uyku" to R.drawable.category_uyku,
        "karamsarlik" to R.drawable.category_karamsarlik,
        "huzur" to R.drawable.category_huzur,
        "merak" to R.drawable.category_merak,
        "okumak" to R.drawable.category_okumak,
        "hata" to R.drawable.category_hata,
        "aliskanlik" to R.drawable.category_aliskanlik,
        "sinav" to R.drawable.category_sinav,
    )

    @DrawableRes
    fun kaynak(key: String): Int = all[key] ?: R.drawable.scene_summit
}

/** The category title supplies semantics; the background is intentionally decorative. */
@Composable
fun KategoriGorseli(kategori: String, modifier: Modifier = Modifier) {
    Box(modifier) {
        Image(
            painter = painterResource(KategoriResimleri.kaynak(kategori)),
            contentDescription = null,
            modifier = Modifier.matchParentSize(),
            contentScale = ContentScale.Crop,
        )
        Box(Modifier.matchParentSize().background(Brush.verticalGradient(
            0f to Color(0xFF06171D).copy(alpha = .04f),
            .46f to Color(0xFF06171D).copy(alpha = .10f),
            1f to Color(0xFF06171D).copy(alpha = .82f),
        )))
    }
}
