"""Compile verified locale files into offline tables and Android string resources. No network."""
from pathlib import Path
import json,re,hashlib,unicodedata,sys
import xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]
LANGS=['pt','de','fr','it','ru']
OUT=ROOT/'app/src/main/java/com/yalnizfahrettin/azim/data'
def read(p):return json.loads((ROOT/p).read_text(encoding='utf-8'))
def write(p,text):
 if '--check' in sys.argv: assert p.exists() and p.read_text(encoding='utf-8')==text,f'Stale generated locale: {p.name}'
 else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text,encoding='utf-8')
def kotlin(s):return json.dumps(s,ensure_ascii=False).replace('$','\\$')
def table(name,values):
 pairs=list(values.items());n=(len(pairs)+79)//80
 s=f'    val {name}: Map<String, String> by lazy {{ '+ ' + '.join(f'{name}{i}()' for i in range(n))+' }\n'
 for i in range(n):
  s+=f'    private fun {name}{i}(): Map<String, String> = mapOf(\n'
  s+=''.join(f'        {kotlin(a)} to {kotlin(b)},\n' for a,b in pairs[i*80:(i+1)*80])
  s+='    )\n'
 return s
master=read('content/source.en.json'); ui_source=read('content/ui/source.en.json')
for lang in LANGS:
 data=read(f'content/translations/{lang}.json');ui=read(f'content/ui/{lang}.json')
 assert data['locale']==lang and data['sourceCatalogVersion']==master['catalogVersion']
 assert set(data['quotes'])=={q['id'] for q in master['quotes']}
 assert set(ui)==set(ui_source),f'UI coverage mismatch: {lang}'
 for q in master['quotes']:
  record=data['quotes'][q['id']];s=record['text']
  assert record['sourceHash']==hashlib.sha256(q['text'].encode()).hexdigest()
  assert 20<=len(s)<=300 and s==s.strip() and '\n' not in s and '\ufffd' not in s,(lang,q['id'])
  assert unicodedata.normalize('NFC',s)==s
 assert len({r['text'].casefold() for r in data['quotes'].values()})==len(data['quotes']),f'Duplicate translated content: {lang}'
 for source,target in ui.items():
  assert target and '\ufffd' not in target
  tokens=lambda x:sorted(re.findall(r'\{\d+\}|%\d+\$[dsf]|%[dsf]',x))
  assert tokens(source)==tokens(target),(lang,source,target)
  assert 'ZXQ' not in target and 'QXZ' not in target,(lang,source,target)
 text='package com.yalnizfahrettin.azim.data\n\n// GENERATED by tools/build_locales.py; edit content translations instead.\n'
 text+=f'internal object Locale{lang.title()} {{\n'
 text+=table('quotes',{key:value['text'] for key,value in data['quotes'].items()})
 text+=table('ui',ui)+'}\n'
 write(OUT/f'Locale{lang.title()}.kt',text)
 resources=ET.Element('resources')
 for e in ET.parse(ROOT/'app/src/main/res/values-en/strings.xml').getroot():
  assert e.tag=='string'
  source=''.join(e.itertext()).replace("\\'","'")
  v=ui[source]
  child=ET.SubElement(resources,'string',e.attrib)
  child.text='"'+v.replace('\\','\\\\').replace('"','\\"').replace("'","\\'").replace('\n','\\n')+'"'
 ET.indent(resources,space='    ')
 write(ROOT/f'app/src/main/res/values-{lang}/strings.xml','<?xml version="1.0" encoding="utf-8"?>\n'+ET.tostring(resources,encoding='unicode')+'\n')
text='package com.yalnizfahrettin.azim.data\n\n// GENERATED by tools/build_locales.py. Tables are lazy and shared across all surfaces.\ninternal object LocaleCatalog {\n'
for name in ['quotes','ui']:
 text+=f'    fun {name}(language: String): Map<String, String> = when(language) {{\n'
 text+=''.join(f'        "{lang}" -> Locale{lang.title()}.{name}\n' for lang in LANGS)
 text+='        else -> emptyMap()\n    }\n'
text+='}\n';write(OUT/'LocaleCatalog.kt',text)
print('Five complete offline locales validated: 6,350 content translations and all UI entries.')
