"""Compile the single English master and ID-linked translations into offline Kotlin.

Edit content/source.en.json. Translate into content/translations/<locale>.json.
Run this script, or --check in CI. --template <locale> writes an empty translation
template with English-source fingerprints; it never invents translations.
"""
from pathlib import Path
import argparse, collections, hashlib, json, re, sys, unicodedata

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'app/src/main/java/com/yalnizfahrettin/azim/data/IcerikVerisi.kt'

def fingerprint(text):
    return hashlib.sha256(text.encode('utf-8')).hexdigest()

def norm(text):
    return re.sub(r'\W+', '', unicodedata.normalize('NFC', text).casefold())

def validate_text(text, label):
    assert isinstance(text, str) and 40 <= len(text) <= 120, f'{label}: expected 40–120 characters'
    assert text == text.strip() and '\n' not in text and '\r' not in text, f'{label}: unexpected whitespace'
    assert not any(unicodedata.category(c).startswith('C') for c in text), f'{label}: control character'
    assert unicodedata.normalize('NFC',text)==text, f'{label}: normalize Unicode to NFC'

def read_master():
    master = json.loads((ROOT/'content/source.en.json').read_text(encoding='utf-8'))
    assert master['sourceLanguage']=='en' and master['schemaVersion']==1
    assert master['author']=='Ascend'
    categories = [c['id'] for c in master['categories']]
    groups = [g['id'] for g in master['groups']]
    assert len(categories)==len(set(categories))==70 and len(groups)==len(set(groups))==12
    assert all(c['group'] in groups for c in master['categories'])
    quotes=master['quotes']; ids=[q['id'] for q in quotes]
    assert len(ids)==len(set(ids))==700, 'Expected 700 distinct stable IDs'
    assert collections.Counter(q['category'] for q in quotes)==collections.Counter({c:10 for c in categories})
    for q in quotes:
        assert set(q)=={'id','category','text'}, f'Unexpected source fields in {q}'
        assert re.fullmatch(r'v5_'+re.escape(q['category'])+r'_\d{2}',q['id'])
        validate_text(q['text'],q['id']+' en')
    assert len({norm(q['text']) for q in quotes})==len(quotes), 'Repeated English text'
    return master

def render(master, translation):
    quotes=master['quotes']; target=translation['quotes']
    assert translation['locale']=='tr' and translation['schemaVersion']==1
    assert translation['sourceCatalogVersion']==master['catalogVersion']
    assert set(target)=={q['id'] for q in quotes}, 'Missing or orphaned Turkish IDs'
    for q in quotes:
        record=target[q['id']]
        assert set(record)=={'text','sourceHash'}
        validate_text(record['text'],q['id']+' tr')
        assert record['sourceHash']==fingerprint(q['text']), f'Stale translation: {q["id"]}'
    assert len({norm(r['text']) for r in target.values()})==len(quotes), 'Repeated Turkish text'
    quote=lambda text:json.dumps(text,ensure_ascii=False).replace('$','\\$')
    result='package com.yalnizfahrettin.azim.data\n\n// GENERATED by tools/icerik_derle.py. Edit content/source.en.json and translations.\ninternal object IcerikVerisi {\n'
    result+='    val tumu: List<Soz> by lazy { '+ ' + '.join(f'bolum{i}()' for i in range(7))+' }\n'
    for index in range(7):
        result+=f'    private fun bolum{index}(): List<Soz> = listOf(\n'
        for q in quotes[index*100:(index+1)*100]:
            result+=f'        Soz({quote(target[q["id"]]["text"])}, {quote(q["text"])}, "Ascend", {quote(q["category"])}, sabitKimlik = {quote(q["id"])}),\n'
        result+='    )\n'
    return result+'}\n'

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');parser.add_argument('--template');parser.add_argument('--output',type=Path)
    args=parser.parse_args();master=read_master()
    if args.template:
        assert re.fullmatch(r'[a-z]{2,3}(?:-[A-Za-z]{2,4})?',args.template), 'Use a language code such as de or pt-BR'
        assert args.output is not None, '--output is required; existing translations are never overwritten'
        template={'schemaVersion':1,'locale':args.template,'sourceCatalogVersion':master['catalogVersion'],'quotes':{q['id']:{'text':'','sourceHash':fingerprint(q['text'])} for q in master['quotes']}}
        with args.output.open('x',encoding='utf-8') as file:json.dump(template,file,ensure_ascii=False,indent=2)
        print('Empty translation template created. Refer to English master by ID.');return
    translation=json.loads((ROOT/'content/translations/tr.json').read_text(encoding='utf-8'))
    result=render(master,translation)
    if args.check:
        assert TARGET.exists() and TARGET.read_text(encoding='utf-8')==result, 'Generated Kotlin differs; run python tools/icerik_derle.py'
    else:TARGET.write_text(result,encoding='utf-8')
    print('700 English originals, 700 linked Turkish translations, 70 categories, no duplicates or stale translations.')

if __name__=='__main__':
    try:main()
    except (AssertionError, KeyError, ValueError) as error:
        print(f'Content validation failed: {error}',file=sys.stderr);sys.exit(1)
