"""Compile content/classics.json (verbatim public-domain quotes) into KlasikVerisi.kt.

--check   fail if the generated Kotlin is stale
--verify  download each source text and require every quote to appear in it verbatim
          (whitespace, footnote markers, quote marks and letter case normalized)
"""
import json, re, sys, unicodedata, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'content/classics.json'
TARGET = ROOT / 'app/src/main/java/com/yalnizfahrettin/azim/data/KlasikVerisi.kt'

def norm(text):
    text = unicodedata.normalize('NFC', text).replace('’', "'").replace('‘', "'").replace('“', '"').replace('”', '"')
    text = re.sub(r'\[\d+\]', '', text)
    return re.sub(r'\s+', ' ', text).strip().casefold()

def load():
    data = json.loads(SOURCE.read_text(encoding='utf-8'))
    sources = data['sources']; quotes = data['quotes']
    categories = {c['id'] for c in json.loads((ROOT / 'content/source.en.json').read_text(encoding='utf-8'))['categories']}
    ids = [q['id'] for q in quotes]
    assert len(ids) == len(set(ids)), 'duplicate classic IDs'
    for q in quotes:
        assert set(q) == {'id', 'category', 'source', 'en', 'tr'}, q['id']
        assert re.fullmatch(r'pd_' + re.escape(q['category']) + r'_\d{2}', q['id']), q['id']
        assert q['category'] in categories and q['source'] in sources, q['id']
        for lang in ('en', 'tr'):
            t = q[lang]
            assert 20 <= len(t) <= 260 and t == t.strip() and unicodedata.normalize('NFC', t) == t, (q['id'], lang)
    return sources, quotes

def kotlin(sources, quotes):
    s = lambda t: json.dumps(t, ensure_ascii=False).replace('$', '\\$')
    out = ['package com.yalnizfahrettin.azim.data', '', '// GENERATED by tools/klasik_derle.py from content/classics.json.',
           '/** Verbatim public-domain translations; Turkish is Ascend\'s rendering of the English text. */',
           'internal object KlasikVerisi {', '    val tumu: List<Soz> by lazy { listOf(']
    for q in quotes:
        src = sources[q['source']]
        out.append(f'        Soz({s(q["tr"])}, {s(q["en"])}, {s(src.get("authorEn", src["author"]))}, {s(q["category"])}, sabitKimlik = {s(q["id"])}, '
                   f'eser = Eser({s(src["author"])}, {s(src["work"]["tr"])}, {s(src["work"]["en"])}, {s(src["translator"])}, {s(src["reference"])})),')
    out += ['    ) }', '}', '']
    return '\n'.join(out)

def verify(sources, quotes):
    texts = {}
    for key, src in sources.items():
        with urllib.request.urlopen(src['url'], timeout=60) as response:
            texts[key] = norm(response.read().decode('utf-8', 'ignore'))
    # A quote may end where the source sentence continues, so its final mark is not required.
    missing = [q['id'] for q in quotes if norm(q['en']).rstrip('.!?;') not in texts[q['source']]]
    assert not missing, f'Not found verbatim in source: {missing}'
    print(f'{len(quotes)} classic quotes verified verbatim against {len(sources)} public-domain sources.')

def main():
    sources, quotes = load()
    result = kotlin(sources, quotes)
    if '--verify' in sys.argv: verify(sources, quotes)
    if '--check' in sys.argv:
        assert TARGET.exists() and TARGET.read_text(encoding='utf-8') == result, 'KlasikVerisi.kt is stale; run python tools/klasik_derle.py'
    else:
        TARGET.write_text(result, encoding='utf-8')
    print(f'{len(quotes)} classic quotes compiled.')

if __name__ == '__main__':
    try: main()
    except AssertionError as e: print(f'Classics validation failed: {e}', file=sys.stderr); sys.exit(1)
