#!/usr/bin/env python3
"""Prepare generated category photographs without changing their creative content.

Requires Pillow. Source images stay outside the repository; the JSON map contains
their local paths. Only resized WebP resources, a path-free provenance manifest,
and a statically checked Kotlin resource map are bundled with the Android app.

Example:
  python tools/prepare_category_art.py --map ../category-art-map.json \
      --prompts ../category-art-prompts.json --contact-sheets ../category-art-qa

Use --partial while generation is running. Incomplete inputs may create available
resources/contact sheets, but cannot overwrite the final Kotlin map or manifest.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import textwrap
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps, __version__ as pillow_version

MAX_SIZE = (512, 683)
QUALITY = 82


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8-sig"))


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def font(size: int):
    for path in ("C:/Windows/Fonts/arial.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"):
        if Path(path).is_file():
            return ImageFont.truetype(path, size)
    return ImageFont.load_default(size=size)


def contact_sheets(records: list[dict], sources: dict[str, Path], folder: Path) -> None:
    """Review aid only: label unchanged image thumbnails beside their prompt subjects."""
    folder.mkdir(parents=True, exist_ok=True)
    width, image_height, cell_height, margin = 220, 272, 355, 16
    for start in range(0, len(records), 8):
        page = records[start:start + 8]
        canvas = Image.new("RGB", (width * 4 + margin * 2, cell_height * 2 + margin * 2), "#eef0ec")
        draw = ImageDraw.Draw(canvas)
        for index, record in enumerate(page):
            x = margin + (index % 4) * width
            y = margin + (index // 4) * cell_height
            with Image.open(sources[record["category"]]) as source:
                thumb = ImageOps.exif_transpose(source).convert("RGB")
                thumb.thumbnail((width - 12, image_height), Image.Resampling.LANCZOS)
            canvas.paste(thumb, (x + (width - 12 - thumb.width) // 2, y))
            draw.text((x, y + image_height + 6), record["category"], font=font(15), fill="#10222b")
            subject = record["prompt"].split("Subject: ", 1)[-1]
            for line, text in enumerate(textwrap.wrap(subject, width=29)[:3]):
                draw.text((x, y + image_height + 27 + line * 16), text, font=font(12), fill="#304852")
        canvas.save(folder / f"category-art-{start // 8 + 1:02d}.jpg", quality=92)


def kotlin_map(ids: list[str]) -> str:
    mapping = "\n".join(f'        "{key}" to R.drawable.category_{key},' for key in ids)
    return '''package com.yalnizfahrettin.azim.ui

import androidx.annotation.DrawableRes
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import com.yalnizfahrettin.azim.R

/** Generated by tools/prepare_category_art.py; every catalogue category has its own image. */
object KategoriResimleri {
    val all: Map<String, Int> = mapOf(
''' + mapping + '''
    )

    @DrawableRes
    fun kaynak(key: String): Int = all[key] ?: R.drawable.scene_summit
}

/** The category title supplies semantics; the background is intentionally decorative. */
@Composable
fun KategoriGorseli(kategori: String, modifier: Modifier = Modifier) {
    Box(modifier) {
        Image(
            painter = painterResource(KategoriResimleri.kaynak(kategori)),
            contentDescription = null,
            modifier = Modifier.matchParentSize(),
            contentScale = ContentScale.Crop,
        )
        Box(Modifier.matchParentSize().background(Brush.verticalGradient(
            0f to Color(0xFF06171D).copy(alpha = .04f),
            .46f to Color(0xFF06171D).copy(alpha = .10f),
            1f to Color(0xFF06171D).copy(alpha = .82f),
        )))
    }
}
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--map", type=Path, required=True, dest="mapping")
    parser.add_argument("--prompts", type=Path, required=True)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--contact-sheets", type=Path)
    parser.add_argument("--partial", action="store_true")
    args = parser.parse_args()

    repo = args.repo.resolve()
    prompts = read_json(args.prompts)
    mapping = read_json(args.mapping)
    catalogue = read_json(repo / "content/source.en.json")
    ids = [record["id"] for record in catalogue["categories"]]
    prompts_by_id = {record["id"]: record["prompt"] for record in prompts}
    if len(prompts_by_id) != len(prompts) or set(prompts_by_id) != set(ids):
        parser.error("Prompt IDs must match the English catalogue exactly and be unique")
    if any(not re.fullmatch(r"[a-z][a-z0-9_]*", key) for key in ids):
        parser.error("Category IDs must be valid Android resource suffixes")
    if set(mapping) - set(ids):
        parser.error("Map contains unknown category IDs: " + ", ".join(sorted(set(mapping) - set(ids))))
    sources = {key: Path(value).resolve() for key, value in mapping.items()}
    absent_files = [key for key, path in sources.items() if not path.is_file()]
    if absent_files:
        parser.error("Mapped source images do not exist: " + ", ".join(absent_files))
    missing = [key for key in ids if key not in sources]
    if missing and not args.partial:
        parser.error("Missing category images (use --partial only for preparation): " + ", ".join(missing))
    if len(set(sources.values())) != len(sources):
        parser.error("Two categories map to the same source path")
    source_hashes = {key: digest(path) for key, path in sources.items()}
    if len(set(source_hashes.values())) != len(source_hashes):
        parser.error("Two category source images have identical bytes")

    output = repo / "app/src/main/res/drawable-nodpi"
    output.mkdir(parents=True, exist_ok=True)
    records = []
    for key in ids:
        if key not in sources:
            continue
        target = output / f"category_{key}.webp"
        with Image.open(sources[key]) as original:
            source_size = list(original.size)
            image = ImageOps.exif_transpose(original).convert("RGB")
            image.thumbnail(MAX_SIZE, Image.Resampling.LANCZOS)
            image.save(target, "WEBP", quality=QUALITY, method=6, exact=True)
            size = list(image.size)
        records.append({
            "category": key,
            "prompt": prompts_by_id[key],
            "asset": target.relative_to(repo).as_posix(),
            "sourceSize": source_size,
            "sourceSha256": source_hashes[key],
            "size": size,
            "bytes": target.stat().st_size,
            "sha256": digest(target),
        })
    if len({record["sha256"] for record in records}) != len(records):
        parser.error("Prepared category resources must remain distinct")

    if args.contact_sheets:
        contact_sheets(records, sources, args.contact_sheets)
    if not missing:
        code_path = repo / "app/src/main/java/com/yalnizfahrettin/azim/ui/KategoriGorseli.kt"
        code_path.write_text(kotlin_map(ids), encoding="utf-8", newline="\n")
        manifest = {
            "schemaVersion": 1,
            "generator": "image_gen.imagegen",
            "purpose": "Original illustrative category photographs for Ascend",
            "interpretation": "AI-generated editorial illustrations; not verified historical portraits or photographs of specific real sites.",
            "processing": {
                "resize": "Proportional Lanczos thumbnail, no creative retouching or cropping",
                "maximumSize": list(MAX_SIZE),
                "format": "RGB WebP",
                "quality": QUALITY,
                "pillowVersion": pillow_version,
                "metadata": "No local source paths or image metadata are bundled",
            },
            "count": len(records),
            "categories": records,
        }
        (repo / "docs/category-art.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "prepared": len(records),
        "uniqueSourceImages": len(set(source_hashes.values())),
        "uniqueBundledImages": len({record["sha256"] for record in records}),
        "totalBytes": sum(record["bytes"] for record in records),
        "missing": missing,
        "finalManifestWritten": not missing,
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
